--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TheWindows/Pillars
build-by-default: true
branches:
  - main
projects:
  Pillars:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1
    lint:
      php: 8.1
...
