name: Pillars 
version: 1.0.0
main: TheWindows\Pillars\Main
api: 5.0.0
author: TheWindows
depend:
  - MultiWorld
virions:
  - apibossbar
  - libFormAPI
permissions:
  pillars.admin:
    description: "Allows access to Pillars admin commands"
    default: op
  pillars.join:
    description: "Allows players to join Pillars games"
    default: true


